apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
  labels:
   az: us-east-1a
spec:
  containers:
  - image: varunj/myapache:1.0
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
  volumes:
  - name: test-volume
    awsElasticBlockStore:
     volumeID: vol-0f868cc52e31c5a27
     fsType: ext4
